### ISSUE TITLE
No newline character at end of file

### ISSUE THREAD

**Issue by CookieStudios5609** [blurrie/TestTestTest3#1]
# Problem
`penispy.py` lacks a newline character at the end of the file. This violates PEP8, and causes an error symbol to appear on Github when inspecting the source.

# Solution

Add a newline character

**Comment by blurrie** [comment]
Solved in #[bcfbfe1](https://github.com/blurrie/TestTestTest3/commit/bcfbfe1c52792f8417406467233e55a9ebffd1d6)

**Comment by CookieStudios5609** [comment]
Wonderful, thanks!
